In [20]:
import pandas as pd
data = pd.read_csv('data_sppg.csv')
data.head()

,Unnamed: 0,No,Provinsi SPPG,Kab./Kota SPPG,Kecamatan SPPG,Kelurahan/Desa SPPG,Alamat SPPG,Nama SPPG
0,1,1.0,JAWA TENGAH,KEBUMEN,BUAYAN,ADIWARNO,"Jl. Karangbolong,Adiwarno, Kec. Buayan, Kabup...",SPPG Kebumen Buayan Rangkah
1,2,2.0,KALIMANTAN SELATAN,TANAH LAUT,TAMBANG ULANG,SUNGAI PINANG,Jl. Kebun Karet H. Abidin Rt 002 Rw 001 Desa ...,SPPG Tanah Laut Tambang Ulang Sungai Pinang
2,3,3.0,KEPULAUAN RIAU,KOTA BATAM,SAGULUNG,TEMBESI,"Jl Letjen Suprapto, Daerah Mall Top 100 Tembe...",SPPG Kota Batam Sagulung Tembesi 1
3,4,4.0,JAWA TENGAH,KEBUMEN,PREMBUN,TUNGGALROSO,Desa Tunggalroso Kecamatan Prembun Kabupaten ...,SPPG Kebumen Prembun Tunggalroso
4,5,5.0,JAWA BARAT,CIANJUR,SUKALUYU,SINDANGRAJA,Jl. Raya Cibogo Bandung Jonggol sindangraja s...,SPPG Cianjur Sukaluyu Sindangraja

In [2]:
data.columns

Index(['Unnamed: 0', 'No', 'Provinsi SPPG', 'Kab./Kota SPPG', 'Kecamatan SPPG',
       'Kelurahan/Desa SPPG', 'Alamat SPPG', 'Nama SPPG'],
      dtype='object')

In [7]:
data = data.drop('Unnamed: 0',axis=1, index=None)
data.head()

,No,Provinsi SPPG,Kab./Kota SPPG,Kecamatan SPPG,Kelurahan/Desa SPPG,Alamat SPPG,Nama SPPG
0,1.0,JAWA TENGAH,KEBUMEN,BUAYAN,ADIWARNO,"Jl. Karangbolong,Adiwarno, Kec. Buayan, Kabup...",SPPG Kebumen Buayan Rangkah
1,2.0,KALIMANTAN SELATAN,TANAH LAUT,TAMBANG ULANG,SUNGAI PINANG,Jl. Kebun Karet H. Abidin Rt 002 Rw 001 Desa ...,SPPG Tanah Laut Tambang Ulang Sungai Pinang
2,3.0,KEPULAUAN RIAU,KOTA BATAM,SAGULUNG,TEMBESI,"Jl Letjen Suprapto, Daerah Mall Top 100 Tembe...",SPPG Kota Batam Sagulung Tembesi 1
3,4.0,JAWA TENGAH,KEBUMEN,PREMBUN,TUNGGALROSO,Desa Tunggalroso Kecamatan Prembun Kabupaten ...,SPPG Kebumen Prembun Tunggalroso
4,5.0,JAWA BARAT,CIANJUR,SUKALUYU,SINDANGRAJA,Jl. Raya Cibogo Bandung Jonggol sindangraja s...,SPPG Cianjur Sukaluyu Sindangraja

In [18]:
jumlah_perdesa = (
    data.groupby('Alamat SPPG')['Nama SPPG']
    .nunique()
    .reset_index(name='jumlah_sppg_unik')
)

jumlah_perdesa

                                             Alamat SPPG  jumlah_sppg_unik
0       \nJl.Sukaratu Kp.Sindanggalih RT.013 RW.05 De...                 1
1        Akademi Kepolisian,jl Sultan Agung  No.131, ...                 1
2        Balai Panjang, Kec. Payakumbuh Sel., Kota Pa...                 1
3         Biringere, Kabupaten Sinjai, Sulawesi Selatan                  1
4        Desa Cangkringan, RT 013 RW 004, Kecamatan B...                 1
...                                                  ...               ...
27539   ⁠Jl. Merpati 2, Rt 03 Rw 10 No.49, Gunung Sah...                 1
27540   ⁠Jl. Setu Raya 2A Cilangkap, Kec. Cipayung, K...                 1
27541   ⁠Jl. Urip Sumoharjo No. 59 Kel. Kalibalau Ken...                 1
27542   ⁠Kampung Salahaur Rt 06. Rw 10. Kelurahan Cij...                 1
27543   ⁠Kampung Sampai Tengah Rt. 002. Rw. 006 Desa ...                 1

[27544 rows x 2 columns]